# Generated by Django 3.1 on 2020-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('emri', models.CharField(max_length=128)),
                ('kategoria', models.CharField(max_length=255)),
                ('cmimi', models.FloatField()),
                ('sasia', models.PositiveIntegerField(default=50)),
                ('gjendje', models.BooleanField(default=True)),
           ],
        ),
        migrations.CreateModel(
            name='Dyqan',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('emri', models.CharField(max_length=128)),
                ('adresa', models.TextField()),
                ('logo', models.CharField(max_length=255)),
                ('email', models.EmailField(default='anonim@anonim.com', max_length=255)),
                ('produktet', models.ManyToManyField(to='app.Produkt')),
            ],
        ),
    ]
