# Generated by Django 3.1 on 2020-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dyqan',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emri', models.CharField(max_length=255)),
                ('adresa', models.TextField()),
                ('logo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emri', models.CharField(max_length=255)),
                ('kategoria', models.CharField(max_length=255)),
                ('cmimi', models.FloatField()),
                ('dyqani', models.ManyToManyField(to='app.Dyqan')),
            ],
        ),
    ]
