# Generated by Django 3.1 on 2020-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyqan',
            name='email',
            field=models.EmailField(default='anonim@anonim.com', max_length=255),
        ),
    ]
