# Generated by Django 3.1 on 2020-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='dyqani',
            field=models.CharField(default='', max_length=255),
        ),
    ]
